### PR TITLE
Add datepicker functionality

### PR DESCRIPTION
**Pull request by skye2k2**
Add datepicker form elements to one-user-view.ejs and supporting styles, and add back link to all users page.
Add client-side scripts moment.js and pikaday.js to support datepicker functionality.
Add utils.parseUrlParams() function which, given a query string, returns an object containing key/value pairs of all GET parameters.
Modify res.locals object to include the query string to tack onto URLs so we don't lose state when navigating.
NOTE: There are definitely other pages needing similar treatment, but this gets basic functionality working.

### CODE REVIEW

**Comment by crowtherdr** [comment]
I would love to see this get merged!

**Comment by skye2k2** [comment]
I am confused. Why were the datepicker commits not included in your 6667bb007b4b5105d40e564101fb87470b352805 commit?

**Comment by tylerpeterson** [comment]
They're there. I just squashed them.

**Comment by skye2k2** [comment]
Ah. confusing, because of the multiple commits, with only one of them closing the PR.

**Pull request closed without merging**
